### PR TITLE
Prereqs update

### PR DESCRIPTION
**Pull request by gkwan-ibm**
for prereqs change https://github.com/OpenLiberty/guides-common/issues/292

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
hi @Charlotte Holt,

Would you review and approve this PR?  Beside to change "Prerequisites" to "Additional prerequisites", the original content is inaccurate that it only describes 1 tool but says " ... the following tools...” and "First,..."

Before: https://openliberty.io/guides/kubernetes-intro.html#prerequisites
After: http://lgdev1.fyre.ibm.com:4020/guides/kubernetes-intro.html#additional-prerequisites

**Comment by gkwan-ibm** [comment]
hi @Charlotte-Holt,

Would you review this PR?  

Before: https://openliberty.io/guides/kubernetes-intro.html#prerequisites
After: http://lgdev1.fyre.ibm.com:4020/guides/kubernetes-intro.html#additional-prerequisites

**Comment by Charlotte-Holt** [comment]
Hi, @gkwan-ibm - I think that the paragraph change looks good and makes sense, but I'm wondering why we're changing "Prerequisites" to "Additional prerequisites". I know that other guides use the "Prerequisites" section title (https://openliberty.io/guides/cloud-azure.html#prerequisites and https://openliberty.io/guides/cloud-aws.html#prerequisites, for example). To me, "Additional prerequisites" implies that other prerequisites are listed earlier in the guide, but I'm not sure that this is the case.

**Comment by gkwan-ibm** [comment]
hi @Charlotte-Holt
yes, the guides will be changed to have Prereqs, visit https://demo1-openlibertyio.mybluemix.net/guides/kubernetes-intro.html,  there is a small pane for Prereqs at the top of right pane.

**Comment by DannyS03** [comment]
Looks good in master.

**Pull request merged**
